name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: # Supports manual triggering

env:
  CACHE_VERSION: "v1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.12.0.1501
          lein: 2.11.2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ env.CACHE_VERSION }}-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-${{ env.CACHE_VERSION }}-
      - uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          check-latest: true
          cache: 'npm'
          cache-dependency-path: "package-lock.json"
      - run: lein test
      - run: npm ci
      - run: npm run build
      - run: npm test
